# Generated by Django 5.2.7 on 2025-10-11 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='hearing_assist/audio/')),
                ('analysis_type', models.CharField(choices=[('speech_to_text', 'Speech to Text'), ('noise_detection', 'Noise Detection'), ('volume_analysis', 'Volume Analysis'), ('frequency_analysis', 'Frequency Analysis'), ('emotion_detection', 'Emotion Detection')], max_length=20)),
                ('result', models.JSONField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FrequencyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='hearing_assist/frequency/')),
                ('dominant_frequencies', models.JSONField()),
                ('frequency_spectrum', models.JSONField()),
                ('hearing_aid_recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequency_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HearingAidSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amplification_level', models.IntegerField(default=50)),
                ('frequency_adjustments', models.JSONField(default=dict)),
                ('noise_reduction', models.BooleanField(default=True)),
                ('feedback_cancellation', models.BooleanField(default=True)),
                ('directional_microphone', models.BooleanField(default=True)),
                ('tinnitus_masker', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hearing_aid_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HearingAssistSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('microphone', 'Microphone'), ('file_upload', 'File Upload'), ('live_stream', 'Live Stream')], max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_analyses', models.IntegerField(default=0)),
                ('session_data', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearing_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoiseDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='hearing_assist/noise/')),
                ('noise_level', models.FloatField()),
                ('noise_type', models.CharField(choices=[('traffic', 'Traffic'), ('construction', 'Construction'), ('crowd', 'Crowd'), ('music', 'Music'), ('speech', 'Speech'), ('other', 'Other')], max_length=20)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noise_detections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpeechToText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='hearing_assist/speech/')),
                ('transcribed_text', models.TextField()),
                ('language', models.CharField(default='en', max_length=10)),
                ('confidence_score', models.FloatField()),
                ('speaker_count', models.IntegerField(default=1)),
                ('timestamps', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_to_texts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VolumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='hearing_assist/volume/')),
                ('average_volume', models.FloatField()),
                ('peak_volume', models.FloatField()),
                ('volume_consistency', models.CharField(choices=[('very_consistent', 'Very Consistent'), ('consistent', 'Consistent'), ('variable', 'Variable'), ('inconsistent', 'Inconsistent')], max_length=20)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
